### Login and get token
# @name login
POST http://localhost:8080/api/public/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "XH9zk8dNejuK5el5"
}

> {% client.global.set("token", response.body.token); %}

### testdata
POST http://localhost:8080/api/testdata/setup
Authorization: Bearer {{token}}
Content-Type: application/json
