server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/notenverwaltung}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jwt:
    secret: ${JWT_SECRET:defaultSecretKeyForProductionOverride}
    expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    path: /public/docs

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO
    ch.notenverwaltung: INFO
