services:
  notenverwaltung:
    image: ghcr.io/notenverwaltung-ch/notenverwaltung:<version>
    hostname: "api"
    networks:
      - notenverwaltung_productive
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/notenverwaltung
      DB_USERNAME: <username>
      DB_PASSWORD: "<password>"
      JWT_SECRET: <secret>
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

networks:
  notenverwaltung_productive:
    external:
      name: notenverwaltung_productive
