name: CI Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run tests
        run: ./gradlew test

      - name: Create JAR usage instructions
        run: |
          echo "How to run the application JAR" > RUN-README.txt
          echo "" >> RUN-README.txt
          echo "Prerequisites: Java 17 Runtime installed (e.g., Temurin 17)." >> RUN-README.txt
          echo "" >> RUN-README.txt
          echo "Run command:" >> RUN-README.txt
          echo "  java -jar app.jar" >> RUN-README.txt
          echo "" >> RUN-README.txt
          echo "Alternatively, use the Docker image pushed to GHCR (see docker-image-info artifact in the docker job)." >> RUN-README.txt
          echo "" >> RUN-README.txt
          echo "Note: The service listens on port 8080 by default." >> RUN-README.txt
        shell: bash

      - name: Upload build artifacts (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            build/libs/*.jar
            RUN-README.txt

  docker:
    name: Build and push Docker image
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Normalize JAR filename and verify presence
        run: |
          echo "Workspace: $(pwd)"
          ls -la
          echo "Contents of build/libs (after artifact download):" || true
          mkdir -p build/libs
          ls -la build/libs || true

          # Collect possible jar locations. Note: the download-artifact action preserves
          # original paths inside the archive, so downloading to build/libs may create
          # a nested build/libs structure (build/libs/build/libs/*.jar).
          shopt -s nullglob
          JAR_CANDIDATES=(build/libs/*.jar build/libs/build/libs/*.jar)

          COUNT=${#JAR_CANDIDATES[@]}
          if [ "$COUNT" -eq 0 ]; then
            echo "No JAR found after artifact download (checked build/libs and build/libs/build/libs)" >&2
            echo "Tree for debugging:" >&2
            find build -maxdepth 3 -type f -name "*.jar" -print || true
            exit 1
          fi

          # Pick the first candidate and normalize the name to app.jar under build/libs
          SRC_JAR="${JAR_CANDIDATES[0]}"
          echo "Using JAR: $SRC_JAR"
          cp "$SRC_JAR" build/libs/app.jar

          # Copy to repository root so Docker build context surely includes it
          cp build/libs/app.jar ./app.jar
          echo "Root contents after copying app.jar:"
          ls -la
          ls -la build/libs
        shell: bash

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create Docker image usage instructions
        run: |
          echo "Docker image pushed to GHCR" > docker-image-info.txt
          echo "" >> docker-image-info.txt
          echo "Repository: ghcr.io/${GITHUB_REPOSITORY}" >> docker-image-info.txt
          echo "" >> docker-image-info.txt
          echo "Available tags:" >> docker-image-info.txt
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' >> docker-image-info.txt
          echo "" >> docker-image-info.txt
          echo "Pull the image:" >> docker-image-info.txt
          echo "  docker pull ghcr.io/${GITHUB_REPOSITORY}:<tag>" >> docker-image-info.txt
          echo "" >> docker-image-info.txt
          echo "Run the container (maps port 8080):" >> docker-image-info.txt
          echo "  docker run --rm -p 8080:8080 ghcr.io/${GITHUB_REPOSITORY}:<tag>" >> docker-image-info.txt
          echo "" >> docker-image-info.txt
          echo "Note: Replace <tag> with one of the tags listed above." >> docker-image-info.txt
        shell: bash

      - name: Upload Docker image info artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-info
          path: docker-image-info.txt

  latex:
    name: Build and release documentation PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PDF with latex-action
        uses: xu-cheng/latex-action@v3
        with:
          root_file: documentation.tex
          working_directory: documentation
          latexmk_use_lualatex: false
          latexmk_use_xelatex: false
          extra_system_packages: ghostscript
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error
          pre_compile: |
            tlmgr update --self || true
            tlmgr install microtype ltablex ragged2e xurl listingsutf8 babel-german array || true

      - name: Upload PDF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: documentation/documentation.pdf

      - name: Upload LaTeX logs (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: |
            documentation/*.log
            documentation/*.aux
            documentation/*.toc

      - name: Determine version
        id: version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            DATE=$(date +'%Y.%m.%d')
            echo "version=v${DATE}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi
      

      - name: Create GitHub Release (if not exists)
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            documentation/documentation.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
